# Dépendances de notre project que Brownie doit télécharger depuis Github
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    # Ici on dit au compilateur que le "@chainlink" dans nos import correspond à la dépendances que l'on
    # a déclarée au-dessus
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"

dotenv: .env
networks:
  rinkeby:
    eth-usd-price-feed-address: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  ganache-ui:
    verify: False
  developement:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}